[build]
  publish = "build"
  functions = "netlify-functions"

[[redirects]]
  from = "/privacy-policy"
  to = "https://www.ekai.ca/privacyPolicy"
  status = 301
  force = true

[[redirects]]
  from = "/faqs"
  to = "https://www.ekai.ca/FAQs"
  status = 301
  force = true

[[redirects]]
  from = "/terms-of-use"
  to = "https://www.ekai.ca/termsOfUse"
  status = 301
  force = true
